---
language: python
branches:
  only:
    - master
addons:
  apt:
    packages:
      - libhdf5-serial-dev
install:
  - pip install -U pip setuptools tox
  - pip install -r requirements.txt
script:
  - python setup.py pkdeploy
