---
language: python
branches:
  only:
    - master
install:
  - sudo apt-get libhdf5-dev
  - pip install -U pip setuptools tox
  - pip install -r requirements.txt
script:
  - python setup.py pkdeploy
